### ISSUE TITLE
Parse errors after installing plugin and reloading

### ISSUE THREAD

**Issue by TheBricktop** [pixelpen-dev/pixelpen#11]
- **PixelPen Version \*:**  
  0.2.3

- **Godot Version:**
  4.2.2

- **Operating System/Device (including version) \*:**  
  Windows 11

- **Issue Description \*:**  
  
  PixelPen used to work in the same configuration in earlier versions.

- **Steps to Reproduce \*:**  
  after adding to the exisitng project pixel pen throws a lot of parse errors but when installed in empty project it runs allright.

---

- 
![image](https://github.com/pixelpen-dev/pixelpen/assets/3866030/d3bfdf9f-69af-4398-8956-9a81c6236fcd)

**Comment by bayu-sw** [comment]
I did some research an found this PR [Terrain3D #196](https://github.com/TokisanGames/Terrain3D/pull/196), and it seems the issues are similar.

Please test the recent PR #12 
You can download the build artifact [here](https://github.com/pixelpen-dev/pixelpen/actions/runs/9774711340) and let me know if the issue still exist. @TheBricktop

**Comment by d3is** [comment]
This fixed it for me, thank you! 👍
