### ISSUE TITLE
impossible to animate

### ISSUE THREAD

**Issue by JekSun97** [pixelpen-dev/pixelpen#13]
- **PixelPen Version \*:**  
1.0.0

- **Godot Version:**
  4.2.2

- **Issue Description \*:**  
  I created a new frame, and when I press the button to start the animation, nothing happens

**Comment by JekSun97** [comment]
There is also not enough option to change the way you zoom in with the mouse, I’m used to turning the mouse wheel up to zoom in, but this can’t be changed

**Comment by JekSun97** [comment]
I also noticed that almost none of the Animation menu items do anything

**Comment by bayu-sw** [comment]
> I also noticed that almost none of the Animation menu items do anything

I think you didn't move frame from `Draft` to `Timeline` first, Try `Animation >  Use frame in timeline`.

**Comment by bayu-sw** [comment]
> There is also not enough option to change the way you zoom in with the mouse, I’m used to turning the mouse wheel up to zoom in, but this can’t be changed

Please make separate feature proposal, so we can easily track separate issues better, Thankyou
