### ISSUE TITLE
empty window

### ISSUE THREAD

**Issue by csocraman** [pixelpen-dev/pixelpen#8]
- **PixelPen Version \*:**  
  0.2.3

- **Godot Version:**
  4.2.2

- **Operating System/Device (including version) \*:**  
  Windows 11

- **Issue Description \*:**  
  When I open it, there is just an empty window that I can't close, even without the plugin activated.
![Captura de tela 2024-06-19 073030](https://github.com/pixelpen-dev/pixelpen/assets/172378433/c18b900c-8a09-4efb-a231-ca4427c58acb)

**Comment by bayu-sw** [comment]
Thankyou for your report. Can you confirm that you already follow installation here? https://github.com/pixelpen-dev/pixelpen/releases/tag/v0.2.3

Does this happen also in previous version v0.2.2

**Comment by csocraman** [comment]
Yes, I followed, and this occurred in version 0.2.2. too

**Comment by bayu-sw** [comment]
After restart the project, please set this as your main scene in project settings 
'res://addons/net.yarvis.pixel_pen/editor/editor_main_ui.tscn'. Run the project with ▶️ button just like regular game project. Look for any error that occurred in the output and report it here. Thankyou

**Comment by JekSun97** [comment]
The new version doesn't work for me at all.
![22](https://github.com/pixelpen-dev/pixelpen/assets/130399274/77e30ce0-04c6-4087-84a5-6a95397e48fd)

**Comment by bayu-sw** [comment]
@JekSun97 This error typically occurs the first time the plugin is added because Godot does not recognize GDExtension classes. Therefore, a project restart is required. I use macOS, so any errors on the Windows side are difficult for me to debug. I will test it when I get a chance to use Windows.

**Comment by csocraman** [comment]
> After restart the project, please set this as your main scene in project settings 'res://addons/net.yarvis.pixel_pen/editor/editor_main_ui.tscn'. Run the project with ▶️ button just like regular game project. Look for any error that occurred in the output and report it here. Thankyou

it now worked

**Comment by JekSun97** [comment]
@bayu-sw 
The plugin still doesn't work for me.
Godot 4.2.2, I launch the project from the Project folder.
Pixelpen v1.0.0
![1](https://github.com/user-attachments/assets/ddbffe6f-7a59-401e-8b67-fc46c2fb66cc)
![2](https://github.com/user-attachments/assets/72958949-ff07-44e1-bd09-475545c92729)
I restarted the project 4 times and it didn't change anything...
